import { ResourceOptions } from "adminjs";

const risksNavigation = {
  name: "Gestão",
  icon: "Roadmap",
};

export const riskResourceOptions: ResourceOptions = {
  navigation: risksNavigation,
  editProperties: [
    "areaId",
    "userId",
    "types_originId",
    "risks_originId",
    "name",
    "periodId",
    "event",
    "cause",
    "consequence",
    "categoryId",
    "probabilityId",
    "impactId",
    "priority",
  ],
  filterProperties: [
    "areaId",
    "userId",
    "types_originId",
    "risks_originId",
    "name",
    "periodId",
    "event",
    "cause",
    "consequence",
    "categoryId",
    "probabilityId",
    "impactId",
    "priority",
    "createdAt",
  ],
  listProperties: [
    "id",
    "userId",
    "types_originId",
    "risks_originId",
    "name",
    "probabilityId",
    "impactId",
  ],
  showProperties: [
    "id",
    "areaId",
    "userId",
    "types_originId",
    "risks_originId",
    "name",
    "periodId",
    "event",
    "cause",
    "consequence",
    "categoryId",
    "probabilityId",
    "impactId",
    "priority",
    "createdAt",
    "updatedAt",
  ],
};
